apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  # project: team1-project
  source:
    repoURL: https://github.com/NaveenKumar-Y/kubernetes
    targetRevision: HEAD
    path: Helm/FastApi_app  # Your Helm chart folder
    ref: config-source # Alias for Git source
    helm:
      valueFiles:
      # $config-source always refers to the ROOT of the Git repo
      - $config-source/applications/team1/values-dev.yaml
      # - values-dev.yaml  # Or whatever your dev values file is --> this refers file in the targetPath
  destination:
    server: https://kubernetes.default.svc
    namespace: app1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true





# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: fastapi-app
#   namespace: argocd # Must match the namespace where Argo CD is installed
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io # Optional: enables cascading deletes
# spec:
#   project: team1-project # The Argo CD project the app belongs to

#   source:
#     repoURL: https://github.com/NaveenKumar-Y/kubernetes
#     targetRevision: HEAD
#     path: ./FastApi_app # Path to the manifests within the repository

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: app1 # The target K8s namespace for the deployed app

#   syncPolicy:
#     syncOptions:
#       - CreateNamespace=true # Automatically create the target namespace if it doesn't exist
#   #   automated:
#   #     prune: true # Allows Argo CD to delete resources that are no longer in Git
#   #     selfHeal: true # Allows Argo CD to sync live state to desired state if it drifts
